namespace ArmadilloAssault.Configuration.Menus
{
    public enum MenuAction
    {
        nothing,
        back,
        navigate_to,
        start_client,
        stop_client,
        start_server,
        stop_server,
        start_game,
        open_tutorial,
        open_editor,
        toggle_fullscreen,
        toggle_music,
        toggle_sound_effects,
        select_avatar,
        avatar_select,
        level_select,
        prev_level,
        next_level,
        exit,
        end_game,
        end_pause,
        prev_mode,
        next_mode,
        mode_select,
        increment_team_index
    }
}
